
package org.engsoft.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILivraria", targetNamespace = "http://webservice.engsoft.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILivraria {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.engsoft.webservice.Livro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pesquisa", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.Pesquisa")
    @ResponseWrapper(localName = "pesquisaResponse", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.PesquisaResponse")
    @Action(input = "http://webservice.engsoft.org/ILivraria/pesquisaRequest", output = "http://webservice.engsoft.org/ILivraria/pesquisaResponse")
    public Livro pesquisa(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "fazLivros", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.FazLivros")
    @ResponseWrapper(localName = "fazLivrosResponse", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.FazLivrosResponse")
    @Action(input = "http://webservice.engsoft.org/ILivraria/fazLivrosRequest", output = "http://webservice.engsoft.org/ILivraria/fazLivrosResponse")
    public void fazLivros();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.engsoft.webservice.Livro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pesquisa1", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.Pesquisa1")
    @ResponseWrapper(localName = "pesquisa1Response", targetNamespace = "http://webservice.engsoft.org/", className = "org.engsoft.webservice.Pesquisa1Response")
    @Action(input = "http://webservice.engsoft.org/ILivraria/pesquisa1Request", output = "http://webservice.engsoft.org/ILivraria/pesquisa1Response")
    public Livro pesquisa1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
