
package org.engsoft.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivrariaService", targetNamespace = "http://webservice.engsoft.org/", wsdlLocation = "http://localhost:8081/WS/ILivraria?wsdl")
public class LivrariaService
    extends Service
{

    private final static URL LIVRARIASERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVRARIASERVICE_EXCEPTION;
    private final static QName LIVRARIASERVICE_QNAME = new QName("http://webservice.engsoft.org/", "LivrariaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WS/ILivraria?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRARIASERVICE_WSDL_LOCATION = url;
        LIVRARIASERVICE_EXCEPTION = e;
    }

    public LivrariaService() {
        super(__getWsdlLocation(), LIVRARIASERVICE_QNAME);
    }

    public LivrariaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVRARIASERVICE_QNAME, features);
    }

    public LivrariaService(URL wsdlLocation) {
        super(wsdlLocation, LIVRARIASERVICE_QNAME);
    }

    public LivrariaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVRARIASERVICE_QNAME, features);
    }

    public LivrariaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivrariaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILivraria
     */
    @WebEndpoint(name = "LivrariaPort")
    public ILivraria getLivrariaPort() {
        return super.getPort(new QName("http://webservice.engsoft.org/", "LivrariaPort"), ILivraria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILivraria
     */
    @WebEndpoint(name = "LivrariaPort")
    public ILivraria getLivrariaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.engsoft.org/", "LivrariaPort"), ILivraria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRARIASERVICE_EXCEPTION!= null) {
            throw LIVRARIASERVICE_EXCEPTION;
        }
        return LIVRARIASERVICE_WSDL_LOCATION;
    }

}
